# Starter pipeline


trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'poc-personal-sub(993ee1db-8092-4f18-85af-7bbec41b5d45)'
    KeyVaultName: 'akv-test-endpoint'
    SecretsFilter: '*'
    RunAsPreJob: false

- task: CmdLine@2
  inputs:
    script: 'echo $(sqldbconnstring)'

- task: CmdLine@2
  inputs:
    script: 'echo $(sqldbconnstring) > secret.txt'

- task: CopyFiles@2
  inputs:
    Contents: secret.txt
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

